#!/usr/bin/env python

import stdeb.cli_runner
import sys

USAGE = """\
usage: py2dsc [options] distfile
   or: py2dsc --help

where distfile is a .zip or .tar.gz file built with the sdist command
of distutils.
"""


def main():
    sys.exit(stdeb.cli_runner.runit(cmd='sdist_dsc', usage=USAGE))


if __name__ == '__main__':
    main()
