#!/usr/bin/env python
import sys
from optparse import OptionParser
from stdeb.downloader import myprint, get_source_tarball

def main():
    usage = '%prog PACKAGE_NAME [options]'
    parser = OptionParser(usage)
    parser.add_option('--verbose', type='int',
                      help='verbosity level',
                      default=0)
    (options, args) = parser.parse_args()
    if len(args) != 1:
        myprint('need exactly one PACKAGE_NAME',fd=sys.stderr)
        parser.print_help()
        sys.exit(1)

    package_name = args[0]

    tarball_fname = get_source_tarball(package_name,verbose=options.verbose)
    myprint('OK: %s' % tarball_fname)

if __name__=='__main__':
    main()
